version: '2'
services:
  dev:
    image: victor/node-web-app
    container_name: public_app
    ports:
     - "80:3000"
    volumes:
     - .:/app
     - ../.env:/app/.env
     - dev-data:/data
     - /var/lib/docker/volumes/dev-data/_data/public_app/node_modules:/app/node_modules
    command: bash
    stdin_open: true
    tty: true
    environment:
      NODE_PATH: /data/public_app/node_modules
volumes:
  dev-data:
    external: true
